version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mantentimiento-urbano
    ports:
      - "3000:80"
    restart: unless-stopped
    # Opcional: Montar volumen para desarrollo
    # volumes:
    #   - ./dist:/usr/share/nginx/html
